name: Refresh stream content

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: version-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm --version

      - name: Run fetcher
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_CHANNEL_LOGIN: usaginetwork
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        run: |
          node scripts/fetch-stream-data.cjs

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit";
          else
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add assets/data/stream/*.json
            git commit -m "chore(data): refresh stream JSON"
            git push origin HEAD:version-1
          fi
